version: '2'
services:
  web:
    build: .
    command: nodemon --ignore client/ index
    ports:
      - "8080:3000"
    volumes:
      - .:/app/
    environment:
      - NODE_ENV=dev
      - APP_DOMAIN=http://localhost:8080
      - APP_SECRET=secret
      - TW_API_KEY=HGcZ3HPkCK6BhH1zIP7dk0BIJ
      - TW_API_SECRET=6NaJDm1eNw2Qa2aFUPoxgh93AXY8J5js1ovflCxDGCCu1iWBHB
      - DB_HOST=db
      - DB_PORT=27017
      - DB_DATABASE=trackitdb
    links:
      - db
  tdd:
    build: .
    command: npm test
    volumes:
      - .:/app/
    environment:
      - NODE_ENV=test
      - APP_DOMAIN=http://localhost:8080
      - APP_SECRET=secret
      - TW_API_KEY=token
      - TW_API_SECRET=secret
      - DB_HOST=db
      - DB_PORT=27017
      - DB_DATABASE=trackitdb
    links:
      - db
  production:
    build: .
    ports:
      - "80:4000"
    environment:
      - APP_SECRET=08cJj2s88VcX9Zx87Y2zAv1N1Wt2JrbC
      - APP_DOMAIN=http://localhost
      - TW_API_KEY=HGcZ3HPkCK6BhH1zIP7dk0BIJ
      - TW_API_SECRET=6NaJDm1eNw2Qa2aFUPoxgh93AXY8J5js1ovflCxDGCCu1iWBHB
      - DB_HOST=db
      - DB_PORT=27017
      - DB_DATABASE=trackitdb
    links:
      - db
  db:
    image: mongo
    volumes:
      - dbvolume:/data/db
volumes:
  dbvolume:
